"""DICOM conversion execution wrapper — preflight only, disabled by default.

Reads project metadata and conversion dry-run mappings.  Builds dcm2niix
command templates, runs preflight safety checks, and returns a disabled
execution response.

**Real dcm2niix execution is DISABLED in this phase.**
No subprocess is spawned.  No NIfTI files are written.  No rawdata is
modified.  No external tools are called.

Reference:
  docs/DICOM_TO_NIFTI_EXECUTION_WRAPPER_CONTRACT.md
  docs/REAL_PREPROCESSING_EXECUTION_CONTRACT.md
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from src.backend.app.schemas.dicom_conversion_execution import (
    Dcm2niixCommandTemplate,
    DicomConversionExecutionRequest,
    DicomConversionExecutionResponse,
    DicomConversionMapping,
    DicomConversionPreflight,
    DicomConversionSafetyFlags,
    build_dcm2niix_command_template,
    build_disabled_conversion_response,
    is_conversion_execution_enabled,
    summarize_conversion_mappings,
    validate_output_root_not_under_rawdata,
    validate_output_root_under_project,
)
from src.backend.app.services.conversion_planner import plan_conversion
from src.backend.app.services.mock_store import mock_store


def _detect_dcm2niix() -> tuple[bool, str | None, str | None]:
    """Detect whether dcm2niix is available on the system PATH.

    Returns ``(found, executable_path, version_string)``.

    Does NOT execute dcm2niix — uses ``shutil.which`` for path detection
    and ``subprocess`` for version query only when explicitly allowed.
    In this phase, version query is NOT performed.
    """
    import shutil

    exe_path = shutil.which("dcm2niix")
    if exe_path is None:
        return False, None, None
    return True, exe_path, None  # Version query deferred to Phase 4C


def run_conversion_preflight(
    project_id: str,
    request: DicomConversionExecutionRequest | None = None,
) -> DicomConversionPreflight:
    """Run preflight checks for DICOM conversion without executing.

    Reads project metadata, conversion dry-run mappings, and environment
    flags.  Builds command templates.  Does NOT call dcm2niix.  Does NOT
    write files.

    Returns a ``DicomConversionPreflight`` with ``conversion_disabled_by_default=true``.
    """
    warnings: list[str] = []
    errors: list[str] = []
    blocking: list[str] = []

    project = mock_store.get_project(project_id)
    metadata = project.metadata if project and isinstance(project.metadata, dict) else {}
    rawdata_dir = str(metadata.get("rawdata_dir") or "")
    project_dir = str(metadata.get("project_dir") or "")

    # ── 1. Environment flag check ──
    env_flags: dict[str, str] = {}
    for flag in [
        "MEDIMAGE_ENABLE_DICOM_CONVERSION",
        "MEDIMAGE_MATLAB_ENABLED",
        "MEDIMAGE_SPM_SMOKE_ENABLED",
        "MEDIMAGE_ENABLE_REVIEWED_EXECUTION",
        "MEDIMAGE_ENABLE_REAL_PREPROCESSING",
    ]:
        value = os.environ.get(flag, "")
        env_flags[flag] = value

    env_ok, missing_env = is_conversion_execution_enabled(env_flags)
    if not env_ok:
        blocking.append(
            f"Conversion execution blocked: {len(missing_env)} environment "
            f"flag(s) missing: {', '.join(missing_env)}."
        )

    # ── 2. Tool detection ──
    tool_available, exe_path, _tool_version = _detect_dcm2niix()
    if not tool_available:
        blocking.append(
            "dcm2niix was not found on the system PATH. "
            "Install dcm2niix or add it to PATH before conversion."
        )

    # ── 3. Dry-run mappings ──
    try:
        from src.backend.app.schemas.desktop import ConversionDryRunRequest

        dry_run = plan_conversion(
            project_id=project_id,
            request=ConversionDryRunRequest(),
        )
    except Exception as exc:
        errors.append(f"CONVERSION_DRY_RUN_FAILED: {exc}")
        return DicomConversionPreflight(
            ok=False,
            status="blocked",
            conversion_disabled_by_default=True,
            errors=errors,
            blocking_issues=[f"Dry-run failed: {exc}"],
        )

    mappings_dicts = dry_run.mapping_preview
    if not mappings_dicts:
        blocking.append(
            "No conversion mappings were generated by the dry-run planner."
        )

    # ── 4. Convert dry-run mappings to execution mappings ──
    mappings: list[DicomConversionMapping] = []
    for i, md in enumerate(mappings_dicts):
        if isinstance(md, dict):
            mappings.append(DicomConversionMapping(
                source_path=str(md.get("source_path", "")),
                source_type=str(md.get("source_type", "dicom_series")),
                subject_id=md.get("subject_id"),
                session_id=md.get("session_id"),
                modality=str(md.get("modality", "func")),
                suffix=md.get("suffix"),
                task=md.get("task"),
                suggested_relative_path=md.get("suggested_relative_path"),
                confidence=str(md.get("confidence", "high")),
            ))

    # ── 5. Output root safety ──
    output_root = (
        request.output_root
        if request and request.output_root
        else None
    )
    if not output_root and project_dir:
        output_root = str(Path(project_dir) / "converted_bids")

    output_safe = False
    if output_root and project_dir:
        output_safe = validate_output_root_under_project(output_root, project_dir)
        if not output_safe:
            blocking.append(
                f"Output root {output_root} is not under project directory "
                f"{project_dir}."
            )

    if output_root and rawdata_dir:
        if not validate_output_root_not_under_rawdata(output_root, rawdata_dir):
            blocking.append(
                f"Output root {output_root} must not be inside the rawdata "
                f"directory {rawdata_dir}."
            )
            output_safe = False

    # ── 6. Build command templates ──
    command_templates: list[Dcm2niixCommandTemplate] = []
    for i, mapping in enumerate(mappings):
        if not mapping.enabled:
            continue
        input_dir = mapping.source_path
        out_dir = str(Path(output_root or "") / mapping.suggested_relative_path).split("/" + (mapping.suffix or "unknown"))[0] if mapping.suggested_relative_path and output_root else (output_root or "")
        filename = (
            mapping.subject_id + "_task-" + mapping.task + "_" + mapping.suffix
            if mapping.subject_id and mapping.task and mapping.suffix
            else (mapping.suggested_relative_path or "").split("/")[-1].replace(".nii.gz", "")
        )

        template = build_dcm2niix_command_template(
            input_dir=input_dir,
            output_dir=out_dir,
            filename_pattern=filename,
        )
        mapping.output_dir = out_dir
        mapping.output_filename = filename + ".nii.gz"
        command_templates.append(template)

    # ── 7. Determine status ──
    if blocking:
        status: str = "blocked" if not env_ok else "disabled"
    elif not env_ok:
        status = "disabled"
    elif not tool_available:
        status = "disabled"
    elif output_safe and mappings:
        status = "ready"
    else:
        status = "warning"

    mapping_summary = summarize_conversion_mappings(mappings)

    return DicomConversionPreflight(
        ok=len(errors) == 0,
        status=status,  # type: ignore[arg-type]
        conversion_disabled_by_default=not env_ok,
        tool_available=tool_available,
        executable_path=exe_path,
        env_enabled=env_ok,
        missing_env_flags=missing_env,
        approval_required=True,
        audit_required=True,
        output_dir_safe=output_safe,
        output_root_preview=output_root,
        rawdata_readonly=True,
        mapping_count=mapping_summary["total_count"],
        mappings=mappings,
        command_templates=command_templates,
        warnings=warnings,
        errors=errors,
        blocking_issues=blocking,
        safety_flags=DicomConversionSafetyFlags(
            conversion_disabled_by_default=not env_ok,
            env_flags_missing=not env_ok,
        ),
    )


def run_conversion_execute(
    project_id: str,
    request: DicomConversionExecutionRequest,
) -> DicomConversionExecutionResponse:
    """Execute or block DICOM conversion based on gating conditions.

    **In Phase 4B, execution is ALWAYS disabled.**  This function runs
    the preflight and returns a disabled response regardless of env flags.
    No dcm2niix is called.  No files are written.

    When Phase 4C enables real execution, this function will be extended
    to call dcm2niix behind the full approval/audit/manifest/provenance gates.
    """
    preflight = run_conversion_preflight(project_id, request)

    # ── Always disabled in Phase 4B ──
    if preflight.status == "disabled" or preflight.status == "blocked":
        return build_disabled_conversion_response(
            project_id=project_id,
            reason="DICOM conversion execution is blocked by preflight checks.",
            missing_env_flags=preflight.missing_env_flags,
        )

    # ── Future: real execution path (Phase 4C+) ──
    # This block is intentionally unreachable in Phase 4B.
    # When preflight.status == "ready" and all gates pass,
    # the real dcm2niix subprocess will be spawned here.
    # For now, return disabled even when preflight is ready.
    return build_disabled_conversion_response(
        project_id=project_id,
        reason=(
            "DICOM conversion execution is disabled in Phase 4B. "
            "Preflight passed, but real dcm2niix execution requires "
            "Phase 4C (fake/sandbox runner) or later."
        ),
    )


# ═══════════════════════════════════════════════════════════════════════
# 5. Pure helpers (re-exported for convenience)
# ═══════════════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════════════
# 6. Phase 4C-0 — Availability check and sandbox runner
# ═══════════════════════════════════════════════════════════════════════


def check_dcm2niix_availability(
    executable: str = "dcm2niix",
    env: dict[str, str] | None = None,
    runner: Any = None,
) -> "Dcm2niixAvailabilityCheck":
    """Check whether dcm2niix is available and can be queried for version.

    Uses ``shutil.which`` for path detection.  Version query is performed
    only when a ``runner`` callable is explicitly injected (for testing).

    The runner must accept ``[executable, "--version"]`` as an argv list.
    ``shell=True`` is never used.

    Returns a ``Dcm2niixAvailabilityCheck``.
    """
    from datetime import datetime, timezone

    from src.backend.app.schemas.dicom_conversion_execution import (
        Dcm2niixAvailabilityCheck,
        is_conversion_execution_enabled,
        parse_dcm2niix_version,
    )

    import shutil

    warnings: list[str] = []
    errors: list[str] = []
    now = datetime.now(timezone.utc).isoformat()

    env = env or {}
    env_ok, missing_env = is_conversion_execution_enabled(env)

    if not env_ok:
        return Dcm2niixAvailabilityCheck(
            ok=True,
            status="disabled",
            executable=executable,
            env_enabled=False,
            missing_env_flags=missing_env,
            checked_at=now,
            warnings=[f"Environment flags missing: {', '.join(missing_env)}"],
        )

    exe_path = shutil.which(executable)
    if exe_path is None:
        return Dcm2niixAvailabilityCheck(
            ok=True,
            status="missing",
            executable=executable,
            env_enabled=True,
            missing_env_flags=[],
            checked_at=now,
            errors=[f"{executable} not found on system PATH."],
        )

    version: str | None = None
    if runner is not None:
        try:
            result = runner([executable, "--version"])
            stdout = getattr(result, "stdout", "") or ""
            version = parse_dcm2niix_version(stdout)
        except Exception as exc:
            warnings.append(f"Version query failed: {exc}")

    status = "available" if version else "version_failed"

    return Dcm2niixAvailabilityCheck(
        ok=True,
        status=status,  # type: ignore[arg-type]
        executable=executable,
        executable_path=exe_path,
        version=version,
        env_enabled=True,
        missing_env_flags=[],
        checked_at=now,
        warnings=warnings,
        errors=errors,
    )


def run_conversion_sandbox(
    project_id: str,
    request: "DicomConversionExecutionRequest | None" = None,
    *,
    mode: str = "disabled",
    output_root: str | None = None,
    runner: Any = None,
) -> "DicomConversionSandboxResult":
    """Run a fake/sandbox DICOM conversion without calling dcm2niix.

    ``mode`` controls behaviour:
    - ``"disabled"`` — always returns a disabled result (default).
    - ``"fake_outputs"`` — builds command templates and returns placeholder
      artifact paths without writing real files.
    - ``"mock_subprocess"`` — uses the injected ``runner`` to simulate
      dcm2niix execution (for tests only).

    No real dcm2niix is called.  No rawdata is modified.  No NIfTI files
    are written.

    Returns a ``DicomConversionSandboxResult``.
    """
    from src.backend.app.schemas.dicom_conversion_execution import (
        DicomConversionSandboxResult,
        build_disabled_sandbox_result,
    )

    if mode not in {"fake_outputs", "mock_subprocess"}:
        return build_disabled_sandbox_result(
            project_id=project_id,
            reason=f"Sandbox mode '{mode}' is not an active sandbox mode.",
        )

    # Run preflight to get mappings and command templates
    preflight = run_conversion_preflight(project_id, request)

    if preflight.status in ("disabled", "blocked"):
        return DicomConversionSandboxResult(
            ok=False,
            status=preflight.status,  # type: ignore[arg-type]
            mode=mode,  # type: ignore[arg-type]
            project_id=project_id,
            output_root=preflight.output_root_preview,
            mapping_count=preflight.mapping_count,
            command_template_count=len(preflight.command_templates),
            blocking_issues=preflight.blocking_issues,
            safety_flags=preflight.safety_flags,
        )

    # Build fake artifact paths
    out_root = output_root or preflight.output_root_preview or ""
    artifact_count = 0
    manifest_path = None
    provenance_path = None
    stdout_log_path = None
    stderr_log_path = None
    warnings: list[str] = []

    if out_root:
        # Placeholder paths — no files are written in sandbox mode
        manifest_path = str(Path(out_root) / "conversion_output_manifest.json")
        provenance_path = str(Path(out_root) / "conversion_execution_provenance.json")
        stdout_log_path = str(Path(out_root) / "logs" / "dicom_to_nifti_stdout.log")
        stderr_log_path = str(Path(out_root) / "logs" / "dicom_to_nifti_stderr.log")

        # In mock_subprocess mode with a runner, simulate execution
        if mode == "mock_subprocess" and runner is not None:
            try:
                for i, tmpl in enumerate(preflight.command_templates):
                    if i >= 3:  # Limit to 3 for sandbox
                        break
                    argv = [
                        tmpl.executable,
                        "-z", tmpl.compress,
                        "-f", tmpl.filename_pattern,
                    ]
                    if tmpl.bids_sidecar:
                        argv.append("-b")
                    if tmpl.create_bids:
                        argv.append("-ba")
                    argv.extend(tmpl.additional_flags)
                    argv.extend(["-o", tmpl.output_dir, tmpl.input_dir])

                    result = runner(argv)
                    returncode = getattr(result, "returncode", 0)
                    if returncode != 0:
                        stderr = getattr(result, "stderr", "") or ""
                        warnings.append(
                            f"Sandbox command returned {returncode}: {stderr[:200]}"
                        )
            except Exception as exc:
                warnings.append(f"Sandbox runner exception: {exc}")

        artifact_count = 6  # nifti + sidecar × mappings count + manifest + provenance + 2 logs

    return DicomConversionSandboxResult(
        ok=len(preflight.errors) == 0,
        status="succeeded" if not warnings else "warning",
        mode=mode,  # type: ignore[arg-type]
        project_id=project_id,
        output_root=out_root,
        mapping_count=preflight.mapping_count,
        command_template_count=len(preflight.command_templates),
        created_artifact_count=artifact_count,
        manifest_path=manifest_path,
        provenance_path=provenance_path,
        stdout_log_path=stdout_log_path,
        stderr_log_path=stderr_log_path,
        warnings=warnings,
        errors=preflight.errors,
        blocking_issues=preflight.blocking_issues if preflight.status in ("disabled", "blocked") else [],
        safety_flags=preflight.safety_flags,
    )


__all__ = [
    "run_conversion_preflight",
    "run_conversion_execute",
    "run_conversion_sandbox",
    "check_dcm2niix_availability",
    "build_disabled_conversion_response",
]
