"""DICOM conversion execution wrapper — preflight only, disabled by default.

Reads project metadata and conversion dry-run mappings.  Builds dcm2niix
command templates, runs preflight safety checks, and returns a disabled
execution response.

**Real dcm2niix execution is DISABLED in this phase.**
No subprocess is spawned.  No NIfTI files are written.  No rawdata is
modified.  No external tools are called.

Reference:
  docs/DICOM_TO_NIFTI_EXECUTION_WRAPPER_CONTRACT.md
  docs/REAL_PREPROCESSING_EXECUTION_CONTRACT.md
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from src.backend.app.schemas.dicom_conversion_execution import (
    Dcm2niixCommandTemplate,
    DicomConversionExecutionRequest,
    DicomConversionExecutionResponse,
    DicomConversionMapping,
    DicomConversionPreflight,
    DicomConversionSafetyFlags,
    build_dcm2niix_command_template,
    build_disabled_conversion_response,
    is_conversion_execution_enabled,
    summarize_conversion_mappings,
    validate_output_root_not_under_rawdata,
    validate_output_root_under_project,
)
from src.backend.app.services.conversion_planner import plan_conversion
from src.backend.app.services.mock_store import mock_store


def _detect_dcm2niix() -> tuple[bool, str | None, str | None]:
    """Detect whether dcm2niix is available on the system PATH.

    Returns ``(found, executable_path, version_string)``.

    Does NOT execute dcm2niix — uses ``shutil.which`` for path detection
    and ``subprocess`` for version query only when explicitly allowed.
    In this phase, version query is NOT performed.
    """
    import shutil

    exe_path = shutil.which("dcm2niix")
    if exe_path is None:
        return False, None, None
    return True, exe_path, None  # Version query deferred to Phase 4C


def run_conversion_preflight(
    project_id: str,
    request: DicomConversionExecutionRequest | None = None,
) -> DicomConversionPreflight:
    """Run preflight checks for DICOM conversion without executing.

    Reads project metadata, conversion dry-run mappings, and environment
    flags.  Builds command templates.  Does NOT call dcm2niix.  Does NOT
    write files.

    Returns a ``DicomConversionPreflight`` with ``conversion_disabled_by_default=true``.
    """
    warnings: list[str] = []
    errors: list[str] = []
    blocking: list[str] = []

    project = mock_store.get_project(project_id)
    metadata = project.metadata if project and isinstance(project.metadata, dict) else {}
    rawdata_dir = str(metadata.get("rawdata_dir") or "")
    project_dir = str(metadata.get("project_dir") or "")

    # ── 1. Environment flag check ──
    env_flags: dict[str, str] = {}
    for flag in [
        "MEDIMAGE_ENABLE_DICOM_CONVERSION",
        "MEDIMAGE_MATLAB_ENABLED",
        "MEDIMAGE_SPM_SMOKE_ENABLED",
        "MEDIMAGE_ENABLE_REVIEWED_EXECUTION",
        "MEDIMAGE_ENABLE_REAL_PREPROCESSING",
    ]:
        value = os.environ.get(flag, "")
        env_flags[flag] = value

    env_ok, missing_env = is_conversion_execution_enabled(env_flags)
    if not env_ok:
        blocking.append(
            f"Conversion execution blocked: {len(missing_env)} environment "
            f"flag(s) missing: {', '.join(missing_env)}."
        )

    # ── 2. Tool detection ──
    tool_available, exe_path, _tool_version = _detect_dcm2niix()
    if not tool_available:
        blocking.append(
            "dcm2niix was not found on the system PATH. "
            "Install dcm2niix or add it to PATH before conversion."
        )

    # ── 3. Dry-run mappings ──
    try:
        from src.backend.app.schemas.desktop import ConversionDryRunRequest

        dry_run = plan_conversion(
            project_id=project_id,
            request=ConversionDryRunRequest(),
        )
    except Exception as exc:
        errors.append(f"CONVERSION_DRY_RUN_FAILED: {exc}")
        return DicomConversionPreflight(
            ok=False,
            status="blocked",
            conversion_disabled_by_default=True,
            errors=errors,
            blocking_issues=[f"Dry-run failed: {exc}"],
        )

    mappings_dicts = dry_run.mapping_preview
    if not mappings_dicts:
        blocking.append(
            "No conversion mappings were generated by the dry-run planner."
        )

    # ── 4. Convert dry-run mappings to execution mappings ──
    mappings: list[DicomConversionMapping] = []
    for i, md in enumerate(mappings_dicts):
        if isinstance(md, dict):
            mappings.append(DicomConversionMapping(
                source_path=str(md.get("source_path", "")),
                source_type=str(md.get("source_type", "dicom_series")),
                subject_id=md.get("subject_id"),
                session_id=md.get("session_id"),
                modality=str(md.get("modality", "func")),
                suffix=md.get("suffix"),
                task=md.get("task"),
                suggested_relative_path=md.get("suggested_relative_path"),
                confidence=str(md.get("confidence", "high")),
            ))

    # ── 5. Output root safety ──
    output_root = (
        request.output_root
        if request and request.output_root
        else None
    )
    if not output_root and project_dir:
        output_root = str(Path(project_dir) / "converted_bids")

    output_safe = False
    if output_root and project_dir:
        output_safe = validate_output_root_under_project(output_root, project_dir)
        if not output_safe:
            blocking.append(
                f"Output root {output_root} is not under project directory "
                f"{project_dir}."
            )

    if output_root and rawdata_dir:
        if not validate_output_root_not_under_rawdata(output_root, rawdata_dir):
            blocking.append(
                f"Output root {output_root} must not be inside the rawdata "
                f"directory {rawdata_dir}."
            )
            output_safe = False

    # ── 6. Build command templates ──
    command_templates: list[Dcm2niixCommandTemplate] = []
    for i, mapping in enumerate(mappings):
        if not mapping.enabled:
            continue
        input_dir = mapping.source_path
        out_dir = str(Path(output_root or "") / mapping.suggested_relative_path).split("/" + (mapping.suffix or "unknown"))[0] if mapping.suggested_relative_path and output_root else (output_root or "")
        filename = (
            mapping.subject_id + "_task-" + mapping.task + "_" + mapping.suffix
            if mapping.subject_id and mapping.task and mapping.suffix
            else (mapping.suggested_relative_path or "").split("/")[-1].replace(".nii.gz", "")
        )

        template = build_dcm2niix_command_template(
            input_dir=input_dir,
            output_dir=out_dir,
            filename_pattern=filename,
        )
        mapping.output_dir = out_dir
        mapping.output_filename = filename + ".nii.gz"
        command_templates.append(template)

    # ── 7. Determine status ──
    if blocking:
        status: str = "blocked" if not env_ok else "disabled"
    elif not env_ok:
        status = "disabled"
    elif not tool_available:
        status = "disabled"
    elif output_safe and mappings:
        status = "ready"
    else:
        status = "warning"

    mapping_summary = summarize_conversion_mappings(mappings)

    return DicomConversionPreflight(
        ok=len(errors) == 0,
        status=status,  # type: ignore[arg-type]
        conversion_disabled_by_default=not env_ok,
        tool_available=tool_available,
        executable_path=exe_path,
        env_enabled=env_ok,
        missing_env_flags=missing_env,
        approval_required=True,
        audit_required=True,
        output_dir_safe=output_safe,
        output_root_preview=output_root,
        rawdata_readonly=True,
        mapping_count=mapping_summary["total_count"],
        mappings=mappings,
        command_templates=command_templates,
        warnings=warnings,
        errors=errors,
        blocking_issues=blocking,
        safety_flags=DicomConversionSafetyFlags(
            conversion_disabled_by_default=not env_ok,
            env_flags_missing=not env_ok,
        ),
    )


def run_conversion_execute(
    project_id: str,
    request: DicomConversionExecutionRequest,
) -> DicomConversionExecutionResponse:
    """Execute or block DICOM conversion based on gating conditions.

    **In Phase 4B, execution is ALWAYS disabled.**  This function runs
    the preflight and returns a disabled response regardless of env flags.
    No dcm2niix is called.  No files are written.

    When Phase 4C enables real execution, this function will be extended
    to call dcm2niix behind the full approval/audit/manifest/provenance gates.
    """
    preflight = run_conversion_preflight(project_id, request)

    # ── Always disabled in Phase 4B ──
    if preflight.status == "disabled" or preflight.status == "blocked":
        return build_disabled_conversion_response(
            project_id=project_id,
            reason="DICOM conversion execution is blocked by preflight checks.",
            missing_env_flags=preflight.missing_env_flags,
        )

    # ── Future: real execution path (Phase 4C+) ──
    # This block is intentionally unreachable in Phase 4B.
    # When preflight.status == "ready" and all gates pass,
    # the real dcm2niix subprocess will be spawned here.
    # For now, return disabled even when preflight is ready.
    return build_disabled_conversion_response(
        project_id=project_id,
        reason=(
            "DICOM conversion execution is disabled in Phase 4B. "
            "Preflight passed, but real dcm2niix execution requires "
            "Phase 4C (fake/sandbox runner) or later."
        ),
    )


# ═══════════════════════════════════════════════════════════════════════
# 5. Pure helpers (re-exported for convenience)
# ═══════════════════════════════════════════════════════════════════════

# ═══════════════════════════════════════════════════════════════════════
# 6. Phase 4C-0 — Availability check and sandbox runner
# ═══════════════════════════════════════════════════════════════════════


def check_dcm2niix_availability(
    executable: str = "dcm2niix",
    env: dict[str, str] | None = None,
    runner: Any = None,
) -> "Dcm2niixAvailabilityCheck":
    """Check whether dcm2niix is available and can be queried for version.

    Uses ``shutil.which`` for path detection.  Version query is performed
    only when a ``runner`` callable is explicitly injected (for testing).

    The runner must accept ``[executable, "--version"]`` as an argv list.
    ``shell=True`` is never used.

    Returns a ``Dcm2niixAvailabilityCheck``.
    """
    from datetime import datetime, timezone

    from src.backend.app.schemas.dicom_conversion_execution import (
        Dcm2niixAvailabilityCheck,
        is_conversion_execution_enabled,
        parse_dcm2niix_version,
    )

    import shutil

    warnings: list[str] = []
    errors: list[str] = []
    now = datetime.now(timezone.utc).isoformat()

    env = env or {}
    env_ok, missing_env = is_conversion_execution_enabled(env)

    if not env_ok:
        return Dcm2niixAvailabilityCheck(
            ok=True,
            status="disabled",
            executable=executable,
            env_enabled=False,
            missing_env_flags=missing_env,
            checked_at=now,
            warnings=[f"Environment flags missing: {', '.join(missing_env)}"],
        )

    exe_path = shutil.which(executable)
    if exe_path is None:
        return Dcm2niixAvailabilityCheck(
            ok=True,
            status="missing",
            executable=executable,
            env_enabled=True,
            missing_env_flags=[],
            checked_at=now,
            errors=[f"{executable} not found on system PATH."],
        )

    version: str | None = None
    if runner is not None:
        try:
            result = runner([executable, "--version"])
            stdout = getattr(result, "stdout", "") or ""
            version = parse_dcm2niix_version(stdout)
        except Exception as exc:
            warnings.append(f"Version query failed: {exc}")

    status = "available" if version else "version_failed"

    return Dcm2niixAvailabilityCheck(
        ok=True,
        status=status,  # type: ignore[arg-type]
        executable=executable,
        executable_path=exe_path,
        version=version,
        env_enabled=True,
        missing_env_flags=[],
        checked_at=now,
        warnings=warnings,
        errors=errors,
    )


def run_conversion_sandbox(
    project_id: str,
    request: "DicomConversionExecutionRequest | None" = None,
    *,
    mode: str = "disabled",
    output_root: str | None = None,
    runner: Any = None,
) -> "DicomConversionSandboxResult":
    """Run a fake/sandbox DICOM conversion without calling dcm2niix.

    ``mode`` controls behaviour:
    - ``"disabled"`` — always returns a disabled result (default).
    - ``"fake_outputs"`` — builds command templates and returns placeholder
      artifact paths without writing real files.
    - ``"mock_subprocess"`` — uses the injected ``runner`` to simulate
      dcm2niix execution (for tests only).

    No real dcm2niix is called.  No rawdata is modified.  No NIfTI files
    are written.

    Returns a ``DicomConversionSandboxResult``.
    """
    from src.backend.app.schemas.dicom_conversion_execution import (
        DicomConversionSandboxResult,
        build_disabled_sandbox_result,
    )

    if mode not in {"fake_outputs", "mock_subprocess"}:
        return build_disabled_sandbox_result(
            project_id=project_id,
            reason=f"Sandbox mode '{mode}' is not an active sandbox mode.",
        )

    # Run preflight to get mappings and command templates
    preflight = run_conversion_preflight(project_id, request)

    if preflight.status in ("disabled", "blocked"):
        return DicomConversionSandboxResult(
            ok=False,
            status=preflight.status,  # type: ignore[arg-type]
            mode=mode,  # type: ignore[arg-type]
            project_id=project_id,
            output_root=preflight.output_root_preview,
            mapping_count=preflight.mapping_count,
            command_template_count=len(preflight.command_templates),
            blocking_issues=preflight.blocking_issues,
            safety_flags=preflight.safety_flags,
        )

    # Build fake artifact paths
    out_root = output_root or preflight.output_root_preview or ""
    artifact_count = 0
    manifest_path = None
    provenance_path = None
    stdout_log_path = None
    stderr_log_path = None
    warnings: list[str] = []

    if out_root:
        # Placeholder paths — no files are written in sandbox mode
        manifest_path = str(Path(out_root) / "conversion_output_manifest.json")
        provenance_path = str(Path(out_root) / "conversion_execution_provenance.json")
        stdout_log_path = str(Path(out_root) / "logs" / "dicom_to_nifti_stdout.log")
        stderr_log_path = str(Path(out_root) / "logs" / "dicom_to_nifti_stderr.log")

        # In mock_subprocess mode with a runner, simulate execution
        if mode == "mock_subprocess" and runner is not None:
            try:
                for i, tmpl in enumerate(preflight.command_templates):
                    if i >= 3:  # Limit to 3 for sandbox
                        break
                    argv = [
                        tmpl.executable,
                        "-z", tmpl.compress,
                        "-f", tmpl.filename_pattern,
                    ]
                    if tmpl.bids_sidecar:
                        argv.append("-b")
                    if tmpl.create_bids:
                        argv.append("-ba")
                    argv.extend(tmpl.additional_flags)
                    argv.extend(["-o", tmpl.output_dir, tmpl.input_dir])

                    result = runner(argv)
                    returncode = getattr(result, "returncode", 0)
                    if returncode != 0:
                        stderr = getattr(result, "stderr", "") or ""
                        warnings.append(
                            f"Sandbox command returned {returncode}: {stderr[:200]}"
                        )
            except Exception as exc:
                warnings.append(f"Sandbox runner exception: {exc}")

        artifact_count = 6  # nifti + sidecar × mappings count + manifest + provenance + 2 logs

    return DicomConversionSandboxResult(
        ok=len(preflight.errors) == 0,
        status="succeeded" if not warnings else "warning",
        mode=mode,  # type: ignore[arg-type]
        project_id=project_id,
        output_root=out_root,
        mapping_count=preflight.mapping_count,
        command_template_count=len(preflight.command_templates),
        created_artifact_count=artifact_count,
        manifest_path=manifest_path,
        provenance_path=provenance_path,
        stdout_log_path=stdout_log_path,
        stderr_log_path=stderr_log_path,
        warnings=warnings,
        errors=preflight.errors,
        blocking_issues=preflight.blocking_issues if preflight.status in ("disabled", "blocked") else [],
        safety_flags=preflight.safety_flags,
    )


# ═══════════════════════════════════════════════════════════════════════
# 7. Phase 4C-1 — Synthetic dcm2niix smoke
# ═══════════════════════════════════════════════════════════════════════

_SYNTHETIC_SMOKE_ENV_FLAGS: frozenset[str] = frozenset({
    "MEDIMAGE_ENABLE_DICOM_CONVERSION",
    "MEDIMAGE_ENABLE_SYNTHETIC_DICOM_SMOKE",
    "MEDIMAGE_ALLOW_EXTERNAL_TOOL_SMOKE",
    "MEDIMAGE_MATLAB_ENABLED",
    "MEDIMAGE_SPM_SMOKE_ENABLED",
    "MEDIMAGE_ENABLE_REVIEWED_EXECUTION",
    "MEDIMAGE_ENABLE_REAL_PREPROCESSING",
})


def _is_synthetic_smoke_enabled(env: dict[str, str]) -> tuple[bool, list[str]]:
    """Check whether all synthetic smoke env flags are set to '1'."""
    missing = sorted(f for f in _SYNTHETIC_SMOKE_ENV_FLAGS if env.get(f) != "1")
    return len(missing) == 0, missing


def run_synthetic_dcm2niix_smoke(
    input_dir: Path,
    output_root: Path,
    *,
    executable: str = "dcm2niix",
    env: dict[str, str] | None = None,
    runner: Any = None,
) -> "DicomConversionSandboxResult":
    """Run a controlled real dcm2niix smoke test on synthetic DICOM data.

    **Only accepts synthetic/test input paths.**  Refuses paths that look
    like real rawdata.  Requires all synthetic smoke env flags.

    Uses ``check_dcm2niix_availability()`` to verify dcm2niix is on PATH.
    The ``runner`` callable is used for actual execution; in tests it
    should be monkeypatched.

    No real user rawdata is converted.  No files are written outside
    ``output_root``.  ``shell=True`` is never used.

    Returns a ``DicomConversionSandboxResult`` with manifest, provenance,
    and log paths populated after a successful run.
    """
    from src.backend.app.schemas.dicom_conversion_execution import (
        DicomConversionSandboxResult,
        DicomConversionSafetyFlags,
        build_dcm2niix_command_template,
    )
    from src.backend.app.schemas.execution_manifest import (
        ExecutionProvenance,
        OutputManifest,
        OutputManifestItem,
    )

    warnings: list[str] = []
    errors: list[str] = []
    blocking: list[str] = []

    env = env or {}

    # ── 1. Env flag check ──
    smoke_ok, missing_smoke = _is_synthetic_smoke_enabled(env)
    if not smoke_ok:
        return DicomConversionSandboxResult(
            ok=False,
            status="disabled",
            mode="disabled",
            project_id="synthetic_smoke",
            output_root=str(output_root),
            blocking_issues=[
                f"Synthetic smoke blocked: {len(missing_smoke)} env flag(s) "
                f"missing: {', '.join(missing_smoke)}."
            ],
            safety_flags=DicomConversionSafetyFlags(
                conversion_disabled_by_default=True,
                env_flags_missing=True,
            ),
        )

    # ── 2. Input path safety — refuse real rawdata paths ──
    input_str = str(input_dir.resolve())
    blocked_patterns = [
        "DemoData", "FunRaw", "T1Raw", "data\\rawdata",
        "rawdata", "BIDS", "bids",
    ]
    for pattern in blocked_patterns:
        if pattern.lower() in input_str.lower():
            blocking.append(
                f"Input path '{input_str}' appears to be real rawdata. "
                f"Synthetic smoke only accepts synthetic/test input directories."
            )
            break

    if blocking:
        return DicomConversionSandboxResult(
            ok=False,
            status="blocked",
            mode="disabled",
            project_id="synthetic_smoke",
            output_root=str(output_root),
            blocking_issues=blocking,
            safety_flags=DicomConversionSafetyFlags(
                conversion_disabled_by_default=True,
            ),
        )

    # ── 3. Availability check ──
    availability = check_dcm2niix_availability(
        executable=executable,
        env=env,
        runner=runner,
    )

    if availability.status != "available":
        # Map availability status to DicomConversionStatus
        mapped_status: str = {
            "missing": "blocked",
            "version_failed": "disabled",
            "disabled": "disabled",
            "unknown": "blocked",
        }.get(availability.status, "blocked")

        return DicomConversionSandboxResult(
            ok=False,
            status=mapped_status,  # type: ignore[arg-type]
            mode="disabled",
            project_id="synthetic_smoke",
            output_root=str(output_root),
            blocking_issues=[
                f"dcm2niix not available: status={availability.status}",
            ],
            safety_flags=DicomConversionSafetyFlags(
                conversion_disabled_by_default=True,
            ),
        )

    # ── 4. Build command template ──
    output_root.mkdir(parents=True, exist_ok=True)
    template = build_dcm2niix_command_template(
        input_dir=str(input_dir),
        output_dir=str(output_root),
        filename_pattern="synth_%p",
    )

    # ── 5. Execute (via runner) ──
    logs_dir = output_root / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)
    stdout_log_path = logs_dir / "dcm2niix_stdout.log"
    stderr_log_path = logs_dir / "dcm2niix_stderr.log"

    if runner is not None:
        argv = [
            executable,
            "-z", template.compress,
            "-f", template.filename_pattern,
        ]
        if template.bids_sidecar:
            argv.append("-b")
        if template.create_bids:
            argv.append("-ba")
        argv.extend(template.additional_flags)
        argv.extend(["-o", str(output_root), str(input_dir)])

        try:
            result = runner(argv)
            returncode = getattr(result, "returncode", 0)
            stdout = getattr(result, "stdout", "") or ""
            stderr = getattr(result, "stderr", "") or ""

            stdout_log_path.write_text(stdout, encoding="utf-8", errors="replace")
            stderr_log_path.write_text(stderr, encoding="utf-8", errors="replace")

            if returncode != 0:
                warnings.append(
                    f"dcm2niix returned exit code {returncode}: {stderr[:300]}"
                )
        except Exception as exc:
            errors.append(f"Synthetic smoke execution failed: {exc}")
            return DicomConversionSandboxResult(
                ok=False,
                status="failed",
                mode="mock_subprocess",
                project_id="synthetic_smoke",
                output_root=str(output_root),
                errors=errors,
                safety_flags=DicomConversionSafetyFlags(),
            )

    # ── 6. Write manifest and provenance ──
    manifest_path = output_root / "conversion_output_manifest.json"
    provenance_path = output_root / "conversion_execution_provenance.json"

    # Discover what was actually produced
    produced_items: list[OutputManifestItem] = []
    for p in sorted(output_root.rglob("*")):
        if p.is_file() and p.suffix in {".nii", ".gz", ".json"}:
            info = p.stat()
            produced_items.append(OutputManifestItem(
                kind="nifti" if p.suffix in {".nii", ".gz"} else "json",
                path=str(p),
                relative_path=str(p.relative_to(output_root)),
                required=True,
                exists=True,
                verified=True,
                verification_status="verified",
                size_bytes=info.st_size,
                previewable=p.suffix == ".json",
            ))

    # Add log items
    for log_path in [stdout_log_path, stderr_log_path]:
        if log_path.exists():
            produced_items.append(OutputManifestItem(
                kind="stdout_log" if "stdout" in log_path.name else "stderr_log",
                path=str(log_path),
                relative_path=str(log_path.relative_to(output_root)),
                required=False,
                exists=True,
                verified=True,
                verification_status="verified",
                size_bytes=log_path.stat().st_size,
                previewable=True,
            ))

    manifest = OutputManifest(
        project_id="synthetic_smoke",
        run_id="smoke_001",
        node_id="dicom_to_nifti",
        output_root=str(output_root),
        items=produced_items,
        missing_required_count=sum(
            1 for i in produced_items if i.required and not i.exists
        ),
        verified_count=sum(1 for i in produced_items if i.verified),
    )
    manifest_path.write_text(manifest.model_dump_json(indent=2), encoding="utf-8")

    provenance = ExecutionProvenance(
        project_id="synthetic_smoke",
        run_id="smoke_001",
        node_id="dicom_to_nifti",
        backend="external",
        command_template_id="dcm2niix_smoke",
        params={"filename_pattern": template.filename_pattern},
        input_paths=[str(input_dir)],
        output_paths=[str(p) for p in output_root.rglob("*") if p.is_file()],
        software_versions={"dcm2niix": availability.version or "unknown"},
        return_code=0,
        stdout_log_path=str(stdout_log_path),
        stderr_log_path=str(stderr_log_path),
    )
    provenance_path.write_text(provenance.model_dump_json(indent=2), encoding="utf-8")

    return DicomConversionSandboxResult(
        ok=len(errors) == 0,
        status="succeeded" if not warnings and not errors else "warning",
        mode="mock_subprocess",
        project_id="synthetic_smoke",
        output_root=str(output_root),
        mapping_count=1,
        command_template_count=1,
        created_artifact_count=len(produced_items),
        manifest_path=str(manifest_path),
        provenance_path=str(provenance_path),
        stdout_log_path=str(stdout_log_path),
        stderr_log_path=str(stderr_log_path),
        warnings=warnings,
        errors=errors,
        safety_flags=DicomConversionSafetyFlags(
            conversion_disabled_by_default=False,
            env_flags_missing=False,
        ),
    )


# ═══════════════════════════════════════════════════════════════════════
# 7b. Phase 4H-0 — Real dcm2niix smoke on synthetic DICOM only
# ═══════════════════════════════════════════════════════════════════════

_REAL_SMOKE_ENV_FLAGS: frozenset[str] = frozenset({
    "MEDIMAGE_ENABLE_DICOM_CONVERSION",
    "MEDIMAGE_ENABLE_SYNTHETIC_DICOM_SMOKE",
    "MEDIMAGE_ALLOW_EXTERNAL_TOOL_SMOKE",
    "MEDIMAGE_ALLOW_PERSISTED_SYNTHETIC_CONVERSION",
    "MEDIMAGE_ALLOW_REAL_DCM2NIIX_SMOKE",
    "MEDIMAGE_MATLAB_ENABLED",
    "MEDIMAGE_SPM_SMOKE_ENABLED",
    "MEDIMAGE_ENABLE_REVIEWED_EXECUTION",
    "MEDIMAGE_ENABLE_REAL_PREPROCESSING",
})


def _is_real_smoke_enabled(env: dict[str, str]) -> tuple[bool, list[str]]:
    missing = sorted(f for f in _REAL_SMOKE_ENV_FLAGS if env.get(f) != "1")
    return len(missing) == 0, missing


def run_real_dcm2niix_synthetic_smoke(
    input_dir: Path,
    output_root: Path,
    *,
    executable: str = "dcm2niix",
    env: dict[str, str] | None = None,
) -> "DicomConversionSandboxResult":
    """Run REAL dcm2niix via subprocess on synthetic DICOM only.

    **This is the first function that may call subprocess.run().**
    It is gated behind 9 env flags, synthetic-only input validation,
    dcm2niix availability check, and output root safety.

    Does NOT convert user rawdata.  Subprocess execution is via argv list only.
    Returns a ``DicomConversionSandboxResult``.
    """
    import subprocess

    from src.backend.app.schemas.dicom_conversion_execution import (
        DicomConversionSafetyFlags,
        DicomConversionSandboxResult,
    )
    from src.backend.app.schemas.execution_manifest import (
        ExecutionProvenance,
        OutputManifest,
        OutputManifestItem,
    )

    warnings: list[str] = []
    errors: list[str] = []
    blocking: list[str] = []
    effective_env = os.environ if env is None else env

    # ── 1. Env flag check ──
    ok_flags, missing_flags = _is_real_smoke_enabled(effective_env)
    if not ok_flags:
        return DicomConversionSandboxResult(
            ok=False, status="disabled", mode="disabled",
            project_id="real_smoke",
            blocking_issues=[
                f"Real dcm2niix smoke blocked: {len(missing_flags)} env "
                f"flag(s) missing: {', '.join(missing_flags)}."
            ],
            safety_flags=DicomConversionSafetyFlags(
                conversion_disabled_by_default=True, env_flags_missing=True,
            ),
        )

    # ── 2. Input path safety ──
    input_str = str(input_dir.resolve())
    blocked_patterns = ["DemoData", "FunRaw", "T1Raw", "rawdata", "BIDS"]
    for pattern in blocked_patterns:
        if pattern.lower() in input_str.lower():
            # Allow if explicitly under a synthetic tmp path (pytest tmpdir)
            if "pytest" in input_str.lower() or "tmp" in input_str.lower():
                continue
            blocking.append(
                f"Input path '{input_str}' appears to be real rawdata. "
                f"Real dcm2niix smoke only accepts synthetic/test input."
            )
            break

    if blocking:
        return DicomConversionSandboxResult(
            ok=False, status="blocked", mode="disabled",
            project_id="real_smoke",
            blocking_issues=blocking,
            safety_flags=DicomConversionSafetyFlags(conversion_disabled_by_default=True),
        )

    # ── 3. Availability check ──
    avail = check_dcm2niix_availability(env=effective_env)
    if avail.status != "available":
        return DicomConversionSandboxResult(
            ok=False, status="blocked", mode="disabled", project_id="real_smoke",
            blocking_issues=[f"dcm2niix not available: {avail.status}"],
            safety_flags=DicomConversionSafetyFlags(conversion_disabled_by_default=True),
        )

    # ── 4. Execute real dcm2niix ──
    output_root.mkdir(parents=True, exist_ok=True)
    logs_dir = output_root / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)

    argv = [
        executable, "-z", "y", "-f", "synth_%p_%s", "-b", "-ba",
        "-o", str(output_root), str(input_dir),
    ]

    try:
        result = subprocess.run(argv, capture_output=True, text=True, check=False)
        rc = result.returncode
        stdout = result.stdout or ""
        stderr = result.stderr or ""

        stdout_path = logs_dir / "dcm2niix_stdout.log"
        stderr_path = logs_dir / "dcm2niix_stderr.log"
        stdout_path.write_text(stdout, encoding="utf-8", errors="replace")
        stderr_path.write_text(stderr, encoding="utf-8", errors="replace")

        if rc != 0:
            warnings.append(f"dcm2niix exited with code {rc}: {stderr[:300]}")
    except FileNotFoundError:
        return DicomConversionSandboxResult(
            ok=False, status="failed", mode="disabled", project_id="real_smoke",
            errors=[f"dcm2niix executable not found: {executable}"],
            safety_flags=DicomConversionSafetyFlags(conversion_disabled_by_default=True),
        )
    except Exception as exc:
        return DicomConversionSandboxResult(
            ok=False, status="failed", mode="disabled", project_id="real_smoke",
            errors=[f"Real dcm2niix smoke failed: {exc}"],
            safety_flags=DicomConversionSafetyFlags(conversion_disabled_by_default=True),
        )

    # ── 5. Write manifest and provenance ──
    manifest_path = output_root / "output_manifest.json"
    provenance_path = output_root / "execution_provenance.json"
    artifacts = 0

    items: list[OutputManifestItem] = []
    for p in sorted(output_root.rglob("*")):
        if p.is_file() and p.suffix in {".nii", ".gz", ".json", ".log"}:
            info = p.stat()
            items.append(OutputManifestItem(
                kind="nifti" if p.suffix in {".nii", ".gz"} else "json",
                path=str(p), relative_path=str(p.relative_to(output_root)),
                required=True, exists=True, verified=True,
                verification_status="verified", size_bytes=info.st_size,
            ))
            artifacts += 1

    manifest = OutputManifest(
        project_id="real_smoke", run_id="smoke_real",
        node_id="dicom_to_nifti", output_root=str(output_root),
        items=items,
        missing_required_count=0,
        verified_count=len(items),
    )
    manifest_path.write_text(manifest.model_dump_json(indent=2), encoding="utf-8")

    provenance = ExecutionProvenance(
        project_id="real_smoke", run_id="smoke_real",
        node_id="dicom_to_nifti", backend="external",
        command_template_id="real_smoke",
        stdout_log_path=str(stdout_path),
        stderr_log_path=str(stderr_path),
        return_code=rc,
    )
    provenance_path.write_text(provenance.model_dump_json(indent=2), encoding="utf-8")

    status = "succeeded" if rc == 0 else "warning"

    return DicomConversionSandboxResult(
        ok=rc == 0,
        status=status,  # type: ignore[arg-type]
        mode="mock_subprocess",
        project_id="real_smoke",
        output_root=str(output_root),
        created_artifact_count=artifacts,
        manifest_path=str(manifest_path),
        provenance_path=str(provenance_path),
        stdout_log_path=str(stdout_path),
        stderr_log_path=str(stderr_path),
        warnings=warnings,
        errors=errors,
        safety_flags=DicomConversionSafetyFlags(
            conversion_disabled_by_default=False,
            env_flags_missing=False,
        ),
    )


# ═══════════════════════════════════════════════════════════════════════
# 8. Phase 4F-0 — Synthetic persisted-package conversion
# ═══════════════════════════════════════════════════════════════════════

_PERSISTED_SYNTHETIC_ENV_FLAGS: frozenset[str] = frozenset({
    "MEDIMAGE_ENABLE_DICOM_CONVERSION",
    "MEDIMAGE_ENABLE_SYNTHETIC_DICOM_SMOKE",
    "MEDIMAGE_ALLOW_EXTERNAL_TOOL_SMOKE",
    "MEDIMAGE_ALLOW_PERSISTED_SYNTHETIC_CONVERSION",
    "MEDIMAGE_MATLAB_ENABLED",
    "MEDIMAGE_SPM_SMOKE_ENABLED",
    "MEDIMAGE_ENABLE_REVIEWED_EXECUTION",
    "MEDIMAGE_ENABLE_REAL_PREPROCESSING",
})


def _is_persisted_synthetic_enabled(env: dict[str, str]) -> tuple[bool, list[str]]:
    missing = sorted(f for f in _PERSISTED_SYNTHETIC_ENV_FLAGS if env.get(f) != "1")
    return len(missing) == 0, missing


def run_synthetic_conversion_from_persisted_package(
    project_id: str,
    conversion_run_id: str,
    *,
    env: dict[str, str] | None = None,
    runner: Any = None,
    synthetic_only: bool = True,
) -> "DicomConversionSandboxResult":
    """Run a controlled real dcm2niix smoke from a persisted approval package.

    Reads the persisted review package, validates approval completeness,
    checks env flags, and executes dcm2niix using command templates from
    the persisted package.  Only accepts synthetic/test input paths.

    **User rawdata conversion remains disabled.**  No real user data is
    converted.  ``shell=True`` is never used.

    Returns a ``DicomConversionSandboxResult`` with updated manifest,
    provenance, and log paths.
    """
    from src.backend.app.schemas.dicom_conversion_approval import (
        DicomConversionApprovalRecord,
        evaluate_conversion_approval_gate,
    )
    from src.backend.app.schemas.dicom_conversion_execution import (
        DicomConversionSafetyFlags,
        DicomConversionSandboxResult,
    )
    from src.backend.app.schemas.execution_manifest import (
        ExecutionProvenance,
        OutputManifest,
        OutputManifestItem,
    )
    from src.backend.app.services.dicom_conversion_review_package import (
        read_conversion_review_package,
    )

    warnings: list[str] = []
    errors: list[str] = []
    blocking: list[str] = []
    effective_env = os.environ if env is None else env

    # ── 1. Env flag check ──
    ok_flags, missing_flags = _is_persisted_synthetic_enabled(effective_env)
    if not ok_flags:
        return DicomConversionSandboxResult(
            ok=False, status="disabled", mode="disabled",
            project_id=project_id,
            blocking_issues=[
                f"Persisted synthetic conversion blocked: {len(missing_flags)} "
                f"env flag(s) missing: {', '.join(missing_flags)}."
            ],
            safety_flags=DicomConversionSafetyFlags(
                conversion_disabled_by_default=True, env_flags_missing=True,
            ),
        )

    # ── 2. Read persisted package ──
    project_dir = env.get("MEDIMAGE_PROJECT_DIR", "")
    pkg = read_conversion_review_package(
        project_id, conversion_run_id, project_dir=project_dir,
    )
    if not pkg.ok:
        return DicomConversionSandboxResult(
            ok=False, status="blocked", mode="disabled",
            project_id=project_id,
            blocking_issues=[f"Review package not readable: {pkg.errors}"],
            safety_flags=DicomConversionSafetyFlags(conversion_disabled_by_default=True),
        )

    # ── 3. Validate required files ──
    required_kinds = {"approval_record", "preflight_snapshot", "mapping_snapshot", "command_templates"}
    missing_kinds = {f.kind for f in pkg.files if not f.exists} & required_kinds
    if missing_kinds:
        return DicomConversionSandboxResult(
            ok=False, status="blocked", mode="disabled",
            project_id=project_id,
            blocking_issues=[f"Required files missing: {', '.join(sorted(missing_kinds))}"],
            safety_flags=DicomConversionSafetyFlags(conversion_disabled_by_default=True),
        )

    # ── 4. Validate approval gate ──
    try:
        approval_json = json.loads(Path(next(f.path for f in pkg.files if f.kind == "approval_record")).read_text())
        approval = DicomConversionApprovalRecord(**approval_json)
    except Exception as exc:
        return DicomConversionSandboxResult(
            ok=False, status="blocked", mode="disabled", project_id=project_id,
            blocking_issues=[f"Failed to parse approval record: {exc}"],
            safety_flags=DicomConversionSafetyFlags(conversion_disabled_by_default=True),
        )

    gate = evaluate_conversion_approval_gate(approval, preflight_ok=True)
    if gate.status != "approved":
        return DicomConversionSandboxResult(
            ok=False, status="blocked", mode="disabled",
            project_id=project_id,
            blocking_issues=[f"Approval gate not passed: {gate.status} — missing: {gate.missing_fields}"],
            safety_flags=DicomConversionSafetyFlags(conversion_disabled_by_default=True),
        )

    # ── 5. Validate input paths are synthetic ──
    mapping_path = next((f.path for f in pkg.files if f.kind == "mapping_snapshot"), "")
    try:
        mappings_data = json.loads(Path(mapping_path).read_text()) if mapping_path else {}
    except Exception:
        mappings_data = {}
    for m in mappings_data.get("mappings", []):
        sp = m.get("source_path", "")
        if synthetic_only:
            blocked_patterns = ["DemoData", "FunRaw", "T1Raw", "rawdata", "BIDS"]
            if any(p.lower() in sp.lower() for p in blocked_patterns):
                return DicomConversionSandboxResult(
                    ok=False, status="blocked", mode="disabled",
                    project_id=project_id,
                    blocking_issues=[f"Source path '{sp}' appears to be real rawdata. Synthetic-only."],
                    safety_flags=DicomConversionSafetyFlags(conversion_disabled_by_default=True),
                )

    # ── 6. dcm2niix availability ──
    avail = check_dcm2niix_availability(env=env, runner=runner if runner else None)
    if avail.status != "available":
        return DicomConversionSandboxResult(
            ok=False, status="blocked", mode="disabled", project_id=project_id,
            blocking_issues=[f"dcm2niix not available: {avail.status}"],
            safety_flags=DicomConversionSafetyFlags(conversion_disabled_by_default=True),
        )

    # ── 7. Execute command templates via runner ──
    output_root = pkg.run_dir or ""
    logs_dir = Path(output_root) / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)
    stdout_log_path = logs_dir / "dcm2niix_stdout.log"
    stderr_log_path = logs_dir / "dcm2niix_stderr.log"
    artifact_count = 0

    if runner is not None:
        tmpl_path = next((f.path for f in pkg.files if f.kind == "command_templates"), "")
        try:
            tmpl_data = json.loads(Path(tmpl_path).read_text()) if tmpl_path else {}
        except Exception:
            tmpl_data = {}
        for tmpl in tmpl_data.get("templates", [])[:1]:  # Limit to first template
            argv = [
                tmpl.get("executable", "dcm2niix"),
                "-z", tmpl.get("compress", "y"),
                "-f", tmpl.get("filename_pattern", "%p_%s"),
            ]
            if tmpl.get("bids_sidecar"):
                argv.append("-b")
            if tmpl.get("create_bids"):
                argv.append("-ba")
            argv.extend(["-o", tmpl.get("output_dir", output_root), tmpl.get("input_dir", "")])
            try:
                result = runner(argv)
                stdout = getattr(result, "stdout", "") or ""
                stderr = getattr(result, "stderr", "") or ""
                rc = getattr(result, "returncode", 0)
                stdout_log_path.write_text(stdout, encoding="utf-8", errors="replace")
                stderr_log_path.write_text(stderr, encoding="utf-8", errors="replace")
                if rc != 0:
                    warnings.append(f"dcm2niix returned {rc}: {stderr[:200]}")
            except Exception as exc:
                errors.append(f"Execution failed: {exc}")

        artifact_count = 6

    # ── 8. Write updated manifest and provenance ──
    manifest_path = Path(output_root) / "output_manifest.json"
    provenance_path = Path(output_root) / "execution_provenance.json"

    items: list[OutputManifestItem] = []
    if Path(output_root).exists():
        for p in sorted(Path(output_root).rglob("*")):
            if p.is_file() and p.suffix in {".nii", ".gz", ".json", ".log"}:
                info = p.stat()
                items.append(OutputManifestItem(
                    kind="nifti" if p.suffix in {".nii", ".gz"} else "json",
                    path=str(p), relative_path=str(p.relative_to(output_root)),
                    required=True, exists=True, verified=True,
                    verification_status="verified", size_bytes=info.st_size,
                ))

    manifest = OutputManifest(
        project_id=project_id, run_id=conversion_run_id,
        node_id="dicom_to_nifti", output_root=output_root,
        items=items,
        missing_required_count=sum(1 for i in items if i.required and not i.exists),
        verified_count=sum(1 for i in items if i.verified),
    )
    manifest_path.write_text(manifest.model_dump_json(indent=2), encoding="utf-8")

    provenance = ExecutionProvenance(
        project_id=project_id, run_id=conversion_run_id,
        node_id="dicom_to_nifti", backend="external",
        command_template_id="persisted_package",
        stdout_log_path=str(stdout_log_path),
        stderr_log_path=str(stderr_log_path),
        return_code=0,
    )
    provenance_path.write_text(provenance.model_dump_json(indent=2), encoding="utf-8")

    return DicomConversionSandboxResult(
        ok=len(errors) == 0,
        status="succeeded" if not warnings and not errors else "warning",
        mode="mock_subprocess",
        project_id=project_id,
        output_root=output_root,
        created_artifact_count=artifact_count,
        manifest_path=str(manifest_path),
        provenance_path=str(provenance_path),
        stdout_log_path=str(stdout_log_path),
        stderr_log_path=str(stderr_log_path),
        warnings=warnings, errors=errors,
        safety_flags=DicomConversionSafetyFlags(
            conversion_disabled_by_default=False, env_flags_missing=False,
        ),
    )


__all__ = [
    "run_conversion_preflight",
    "run_conversion_execute",
    "run_conversion_sandbox",
    "check_dcm2niix_availability",
    "run_synthetic_dcm2niix_smoke",
    "run_synthetic_conversion_from_persisted_package",
    "build_disabled_conversion_response",
]
