"""Read-only rs-fMRI QC planning report generator.

Combines BOLD reference readiness and motion QC readiness into
JSON and Markdown report artifacts.  Writes only to a safe project
report output directory.  Never writes rawdata, never calls external
tools, never computes medical image derivatives.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.backend.app.schemas.desktop import (
    RsfmriQcPlanningReportArtifact,
    RsfmriQcPlanningReportResponse,
)
from src.backend.app.services.bold_reference_readiness import (
    build_bold_reference_readiness,
)
from src.backend.app.services.mock_store import mock_store
from src.backend.app.services.motion_metrics_draft import (
    build_motion_metrics_draft,
)
from src.backend.app.services.motion_qc_readiness import (
    build_motion_qc_readiness,
)

_REPORT_ROOT = Path("outputs/reports/rsfmri_qc_planning")


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _safe_slug(value: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "_-" else "_" for ch in value)[:80]


def _report_dir(project_id: str) -> Path:
    return (_REPORT_ROOT / _safe_slug(project_id)).resolve()


def _write_json(path: Path, data: Any) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    encoded = json.dumps(data, ensure_ascii=False, indent=2)
    path.write_text(encoded, encoding="utf-8")
    return len(encoded.encode("utf-8"))


def _write_markdown(path: Path, text: str) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    encoded = text.encode("utf-8")
    path.write_text(text, encoding="utf-8")
    return len(encoded)


def _build_markdown(
    project_id: str,
    generated_at: str,
    bold: dict[str, Any],
    motion: dict[str, Any],
    metrics: dict[str, Any] | None,
    overall_status: str,
    warnings: list[str],
    next_actions: list[str],
) -> str:
    lines: list[str] = [
        "# rs-fMRI QC Planning Report",
        "",
        f"**Generated:** {generated_at}",
        f"**Project:** `{project_id}`",
        f"**Status:** {overall_status}",
        "",
        "---",
        "",
        "## ⚠️ Research-Use Only",
        "",
        "This report is a **planning artifact** for research workflows only. "
        "It is not a clinical diagnosis or clinical decision product. "
        "No realignment, reference image computation, or SPM/DPABI "
        "preprocessing has been executed.",
        "",
        "---",
        "",
        "## Safety Flags",
        "",
        "| Flag | Value |",
        "|------|-------|",
        "| read_only_inputs | ✅ |",
        "| rawdata_not_modified | ✅ |",
        "| no_realign_executed | ✅ |",
        "| no_reference_image_written | ✅ |",
        "| no_external_tools_executed | ✅ |",
        "| planning_report_only | ✅ |",
        "",
        "---",
        "",
        "## BOLD Reference Readiness",
        "",
        f"**Status:** {bold.get('status', 'unknown')}",
        f"**Candidates:** {bold.get('candidate_count', 0)}",
        f"**Ready:** {bold.get('ready_count', 0)}",
        f"**Warning:** {bold.get('warning_count', 0)}",
        f"**Blocked:** {bold.get('blocked_count', 0)}",
        "",
    ]

    bold_candidates = bold.get("candidates", [])
    if bold_candidates:
        lines.extend([
            "### BOLD Candidates",
            "",
            "| Subject | Volumes | Dims | 4D | Sidecar | TR | Task | Strategy |",
            "|---------|---------|------|----|---------|----|------|----------|",
        ])
        for c in bold_candidates[:30]:
            subj = c.get("subject_id") or "-"
            vols = str(c.get("volume_count") or "?")
            dims = "×".join(str(d) for d in c.get("dimensions", [])) or "?"
            is4d = "✓" if c.get("is_4d") else "✗"
            sidecar = "✓" if c.get("has_sidecar") else "✗"
            tr = str(c.get("repetition_time")) + "s" if c.get("repetition_time") else "-"
            task = c.get("task_name") or "-"
            strat = (c.get("reference_strategy") or "?").replace("_", " ")
            lines.append(f"| {subj} | {vols} | {dims} | {is4d} | {sidecar} | {tr} | {task} | {strat} |")
        lines.append("")

    lines.extend([
        "---",
        "",
        "## Motion QC Readiness",
        "",
        f"**Status:** {motion.get('status', 'unknown')}",
        f"**Candidates:** {motion.get('candidate_count', 0)}",
        f"**Missing motion params:** {motion.get('missing_motion_param_count', 0)}",
        f"**FD available:** {motion.get('fd_available_count', 0)}",
        "",
        "> ℹ️ Motion parameters may be generated by future SPM/FSL realignment. "
        "Missing motion params do not block QC planning — they indicate "
        "that realignment has not yet been executed.",
        "",
    ])

    motion_candidates = motion.get("candidates", [])
    if motion_candidates:
        lines.extend([
            "### Motion Candidates",
            "",
            "| Subject | Sidecar | Motion Params | FD Available |",
            "|---------|---------|---------------|--------------|",
        ])
        for c in motion_candidates[:30]:
            subj = c.get("subject_id") or "-"
            sidecar = "✓" if c.get("has_sidecar") else "✗"
            mp = "✓" if c.get("has_motion_params") else "✗"
            fd = "✓" if c.get("has_fd_column") else "✗"
            lines.append(f"| {subj} | {sidecar} | {mp} | {fd} |")
        lines.append("")

    # ── Motion Metrics Draft ──
    if metrics:
        lines.extend([
            "---",
            "",
            "## Motion Metrics Draft Summary",
            "",
            f"**Status:** {metrics.get('status', 'unknown')}",
            f"**Parsed:** {metrics.get('parsed_count', 0)}",
            f"**FD available:** {metrics.get('fd_available_count', 0)}",
            "",
        ])
        metrics_summaries = metrics.get("summaries", [])
        if metrics_summaries:
            lines.extend([
                "### Motion Metrics",
                "",
                "| Subject | Source | Rows | FD | Max Trans (mm) | Max Rot (rad) | FD Mean | FD Max | FD>0.2 | QC Flags |",
                "|---------|--------|------|----|----------------|---------------|---------|--------|--------|----------|",
            ])
            for s in metrics_summaries[:30]:
                subj = s.get("subject_id") or "-"
                src = s.get("source_type", "-")
                rows = str(s.get("row_count", 0))
                fd = "✓" if s.get("has_fd") else "✗"
                mt = f"{s.get('max_abs_translation_mm', '-'):.2f}" if isinstance(s.get("max_abs_translation_mm"), float) else "-"
                mr = f"{s.get('max_abs_rotation_rad', '-'):.4f}" if isinstance(s.get("max_abs_rotation_rad"), float) else "-"
                fdm = f"{s.get('fd_mean', '-'):.3f}" if isinstance(s.get("fd_mean"), float) else "-"
                fdx = f"{s.get('fd_max', '-'):.3f}" if isinstance(s.get("fd_max"), float) else "-"
                fdc = str(s.get("fd_over_0_2_count", "-"))
                qc = "; ".join(s.get("qc_flags", [])[:2]) or "-"
                lines.append(f"| {subj} | {src} | {rows} | {fd} | {mt} | {mr} | {fdm} | {fdx} | {fdc} | {qc} |")
            lines.append("")
        metrics_warnings = metrics.get("warnings", [])
        if metrics_warnings:
            lines.append("> ℹ️ QC flags use 'review suggested' language. "
                         "No clinical interpretation. No subject exclusion.")
            lines.append("")
    else:
        lines.extend([
            "---",
            "",
            "## Motion Metrics Draft Summary",
            "",
            "No motion metrics are available. Run or import motion parameter / "
            "confounds files before computing motion metrics. "
            "Realignment (SPM/FSL) can generate these files.",
            "",
        ])

    if warnings:
        lines.extend(["## Warnings", ""])
        for w in warnings[:20]:
            lines.append(f"- ⚠️ {w}")
        lines.append("")

    if next_actions:
        lines.extend(["## Next Actions", ""])
        for a in next_actions[:10]:
            lines.append(f"- {a}")
        lines.append("")

    lines.extend([
        "---",
        "",
        "## Non-Goals",
        "",
        "- No realignment executed.",
        "- No reference image written.",
        "- No SPM/DPABI execution.",
        "- No rawdata modification.",
        "- No clinical interpretation.",
        "",
        f"*Report generated {generated_at}*",
    ])

    return "\n".join(lines) + "\n"


def build_rsfmri_qc_planning_report(
    project_id: str,
) -> RsfmriQcPlanningReportResponse:
    """Generate QC planning report from BOLD reference + motion QC readiness."""

    now = _now_iso()
    warnings: list[str] = []
    errors: list[str] = []

    project = mock_store.get_project(project_id)
    if project is None:
        return RsfmriQcPlanningReportResponse(
            ok=False, project_id=project_id, status="blocked",
            generated_at=now, report_dir="", json_path="", markdown_path="",
            bold_reference_status="unknown", motion_qc_status="unknown",
            errors=[f"Project not found: {project_id}"],
            safety_flags=_safety_flags(),
        )

    # Fetch readiness data
    bold = build_bold_reference_readiness(project_id)
    motion = build_motion_qc_readiness(project_id)

    # Fetch motion metrics (may fail gracefully — treated as optional)
    metrics = None
    metrics_dict: dict[str, Any] | None = None
    metrics_artifacts: list[dict[str, Any]] = []
    try:
        metrics = build_motion_metrics_draft(project_id)
        metrics_dict = metrics.model_dump()
        metrics_artifacts = [
            {"kind": "json", "path": metrics.json_path, "exists": Path(metrics.json_path).is_file() if metrics.json_path else False, "size_bytes": None},
            {"kind": "markdown", "path": metrics.markdown_path, "exists": Path(metrics.markdown_path).is_file() if metrics.markdown_path else False, "size_bytes": None},
        ]
    except Exception as exc:
        warnings.append(f"Motion metrics unavailable: {exc}")

    bold_dict = bold.model_dump()
    motion_dict = motion.model_dump()

    bold_status = bold_dict.get("status", "unknown")
    motion_status = motion_dict.get("status", "unknown")

    bold_count = bold_dict.get("candidate_count", 0)
    motion_count = motion_dict.get("candidate_count", 0)
    ready_count = bold_dict.get("ready_count", 0)
    blocked_count = bold_dict.get("blocked_count", 0)

    all_warnings: list[str] = []
    all_warnings.extend(bold_dict.get("warnings", [])[:15])
    all_warnings.extend(motion_dict.get("warnings", [])[:15])

    next_actions: list[str] = []
    next_actions.extend(bold_dict.get("next_actions", [])[:5])
    next_actions.extend(motion_dict.get("next_actions", [])[:5])

    # Determine overall status
    metrics_status = metrics_dict.get("status", "unknown") if metrics_dict else "unavailable"
    if bold_status == "blocked":
        overall = "blocked"
    elif bold_status == "warning" or motion_status == "warning" or metrics_status == "warning":
        overall = "warning"
    elif bold_status == "ready":
        overall = "ready"
    else:
        overall = "unknown"

    # Generate report artifacts
    report_dir = _report_dir(project_id)
    safe_dir = str(report_dir.resolve())

    json_data: dict[str, Any] = {
        "project_id": project_id,
        "generated_at": now,
        "status": overall,
        "safety_flags": _safety_flags(),
        "bold_reference_readiness": bold_dict,
        "motion_qc_readiness": motion_dict,
        "motion_metrics": metrics_dict,
        "combined_candidates": {
            "total_bold_candidates": bold_count,
            "total_motion_candidates": motion_count,
            "ready_count": ready_count,
            "blocked_count": blocked_count,
        },
        "warnings": all_warnings[:20],
        "next_actions": next_actions[:10],
        "non_goals": [
            "no realignment executed",
            "no reference image written",
            "no SPM/DPABI execution",
            "no rawdata modification",
            "no clinical interpretation",
        ],
    }

    markdown_text = _build_markdown(
        project_id, now, bold_dict, motion_dict, metrics_dict,
        overall, all_warnings, next_actions,
    )

    json_path = report_dir / "rsfmri_qc_planning_report.json"
    md_path = report_dir / "rsfmri_qc_planning_report.md"

    try:
        json_size = _write_json(json_path, json_data)
    except Exception as exc:
        errors.append(f"JSON_WRITE_FAILED: {exc}")
        json_size = None

    try:
        md_size = _write_markdown(md_path, markdown_text)
    except Exception as exc:
        errors.append(f"MARKDOWN_WRITE_FAILED: {exc}")
        md_size = None

    artifacts: list[dict[str, Any]] = [
        {
            "kind": "json",
            "path": str(json_path),
            "exists": json_path.is_file(),
            "size_bytes": json_size,
        },
        {
            "kind": "markdown",
            "path": str(md_path),
            "exists": md_path.is_file(),
            "size_bytes": md_size,
        },
    ]

    warning_count = len(all_warnings)

    return RsfmriQcPlanningReportResponse(
        ok=len(errors) == 0,
        project_id=project_id,
        status=overall,
        generated_at=now,
        report_dir=safe_dir,
        json_path=str(json_path),
        markdown_path=str(md_path),
        artifacts=[RsfmriQcPlanningReportArtifact(**a) for a in artifacts],
        bold_reference_status=bold_status,
        motion_qc_status=motion_status,
        motion_metrics_status=metrics_status if metrics_dict else None,
        motion_metrics_parsed_count=metrics_dict.get("parsed_count", 0) if metrics_dict else 0,
        motion_metrics_fd_available_count=metrics_dict.get("fd_available_count", 0) if metrics_dict else 0,
        motion_metrics_artifacts=metrics_artifacts,
        bold_candidate_count=bold_count,
        motion_candidate_count=motion_count,
        ready_candidate_count=ready_count,
        warning_count=warning_count,
        blocked_count=blocked_count,
        warnings=all_warnings[:30],
        errors=errors[:20],
        next_actions=next_actions[:10],
        safety_flags=_safety_flags(),
        report_markdown=markdown_text,
    )


def _safety_flags() -> dict[str, bool]:
    return {
        "read_only_inputs": True,
        "rawdata_not_modified": True,
        "no_realign_executed": True,
        "no_reference_image_written": True,
        "no_external_tools_executed": True,
        "planning_report_only": True,
    }
