from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    CONFIG_ERROR = "CONFIG_ERROR"
    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    NOT_FOUND = "NOT_FOUND"
    PIPELINE_ERROR = "PIPELINE_ERROR"
    SAFETY_ERROR = "SAFETY_ERROR"
    STATE_STORE_ERROR = "STATE_STORE_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
