import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";

import type { ProjectDetail } from "../../lib/types/project";
import PlanReviewConsole from "../PlanReviewConsole";
import {
  checkApprovalGate,
  fetchToolCatalog,
  generatePlanFromGoal,
  listProjectReviewedPlans,
  saveReviewedPlan,
} from "../../lib/api/pipeline";

vi.mock("../../lib/api/pipeline", () => ({
  checkApprovalGate: vi.fn(),
  executeReviewedDryRun: vi.fn(),
  executeReviewedPlan: vi.fn(),
  fetchAuditRecord: vi.fn(),
  fetchToolCatalog: vi.fn(),
  generatePlanFromGoal: vi.fn(),
  listProjectReviewedPlans: vi.fn(),
  saveReviewedPlan: vi.fn(),
  validatePlan: vi.fn(),
}));

vi.mock("../../lib/api/client", () => ({ DEFAULT_API_BASE: "http://localhost" }));

const project: ProjectDetail = {
  id: "project-1",
  name: "Demo Project",
  study_id: "study-1",
  modality: "rs-fMRI",
  created_date: "2026-06-25",
  subjects_count: 1,
  current_pipeline_id: "not-selected",
  sequences: ["bold"],
  scans_count: 1,
  total_size: "1 MB",
  current_model_id: "model-1",
  metadata: {
    project_config_path: "work/projects/demo/project_config.yaml",
    rawdata_dir: "work/projects/demo/rawdata",
  },
};

function renderConsole() {
  render(
    <PlanReviewConsole
      selectedProjectId="project-1"
      selectedProject={project}
      projectConfigPath="work/projects/demo/project_config.yaml"
      rawdataDir="work/projects/demo/rawdata"
    />,
  );
}

describe("PlanReviewConsole", () => {
  beforeEach(() => {
    vi.mocked(fetchToolCatalog).mockResolvedValue({ ok: true, count: 0, items: [] });
    vi.mocked(listProjectReviewedPlans).mockResolvedValue({
      ok: true,
      project_id: "project-1",
      reviewed_plans: [],
    });
    vi.mocked(generatePlanFromGoal).mockReset();
    vi.mocked(saveReviewedPlan).mockReset();
    vi.mocked(checkApprovalGate).mockReset();
  });

  it("does not persist generated plans missing reviewed-plan fields", async () => {
    const user = userEvent.setup();
    vi.mocked(generatePlanFromGoal).mockResolvedValue({
      ok: true,
      provider: "mock",
      goal: "motion correction",
      plan: {},
      validation: { ok: false, errors: [] },
      messages: [],
      warnings: [],
      errors: [],
    });

    renderConsole();

    await user.type(screen.getByRole("textbox"), "motion correction");
    await user.click(screen.getByRole("button", { name: "Generate Plan" }));

    expect(
      await screen.findByText(/Generated plan is invalid and was not persisted/i),
    ).toBeInTheDocument();
    expect(saveReviewedPlan).not.toHaveBeenCalled();
  });

  it("shows provider state and blocks real LLM generation when the API key is missing", async () => {
    const user = userEvent.setup();
    vi.mocked(generatePlanFromGoal).mockResolvedValue({
      ok: false,
      provider: "openai_compatible",
      goal: "motion correction",
      plan: {},
      validation: {},
      messages: [],
      warnings: [],
      errors: ["LLM_API_KEY_MISSING"],
    });

    renderConsole();

    expect(screen.getByRole("status")).toHaveTextContent("Mock provider: no external API used");

    await user.selectOptions(screen.getByRole("combobox"), "openai_compatible");
    expect(screen.getByRole("status")).toHaveTextContent("requires MEDIMAGE_LLM_API_KEY");

    await user.type(screen.getByRole("textbox"), "motion correction");
    await user.click(screen.getByRole("button", { name: "Generate Plan" }));

    expect(
      await screen.findByText(/LLM provider disabled: API key not configured/i),
    ).toBeInTheDocument();
    expect(saveReviewedPlan).not.toHaveBeenCalled();
  });

  it("persists a minimal legal reviewed plan generated by the mock provider", async () => {
    const user = userEvent.setup();
    vi.mocked(generatePlanFromGoal).mockResolvedValue({
      ok: true,
      provider: "mock",
      goal: "motion correction",
      plan: {
        pipeline_id: "planned_motion_qc",
        project_context: { project_id: "project-1" },
        goal: "motion correction",
        nodes: [{ id: "data_inspection", backend: "python", params: {}, depends_on: [] }],
        metadata: {
          provider: "mock",
          external_api_used: false,
          execution_enabled: false,
        },
      },
      validation: { ok: true, errors: [] },
      messages: [],
      warnings: [],
      errors: [],
    });
    vi.mocked(saveReviewedPlan).mockResolvedValue({
      ok: true,
      reviewed_plan: {
        reviewed_plan_id: "plan-1",
        project_id: "project-1",
        project_config_path: "work/projects/demo/project_config.yaml",
        dataset_index_path: null,
        rawdata_dir: "work/projects/demo/rawdata",
        plan_hash: "hash",
        plan_path: null,
        status: "reviewed",
        created_at: "2026-06-25T00:00:00Z",
        updated_at: "2026-06-25T00:00:00Z",
        approval_status: "not_requested",
        execution_status: "not_started",
        last_audit_id: null,
        last_execution_id: null,
        warnings: [],
        payload: {},
      },
    });

    renderConsole();

    await user.type(screen.getByRole("textbox"), "motion correction");
    await user.click(screen.getByRole("button", { name: "Generate Plan" }));

    await waitFor(() => expect(saveReviewedPlan).toHaveBeenCalledTimes(1));
    expect(saveReviewedPlan).toHaveBeenCalledWith(
      "http://localhost",
      "project-1",
      expect.objectContaining({
        plan: expect.objectContaining({
          project_context: expect.any(Object),
          goal: "motion correction",
          metadata: expect.any(Object),
        }),
      }),
    );
  });

  it("sends native preprocessing safety acknowledgements to approval gate", async () => {
    const user = userEvent.setup();
    vi.mocked(generatePlanFromGoal).mockResolvedValue({
      ok: true,
      provider: "mock",
      goal: "native full preprocessing",
      plan: {
        pipeline_id: "native_full_preprocessing",
        project_context: { project_id: "project-1" },
        goal: "native full preprocessing",
        nodes: [
          {
            id: "native_preproc_full_execute",
            backend: "native_python",
            params: {},
            depends_on: [],
          },
        ],
        metadata: {
          provider: "mock",
          external_api_used: false,
          execution_enabled: false,
          native_preprocessing: true,
        },
      },
      validation: {
        ok: true,
        errors: [],
        approval_required_nodes: ["native_preproc_full_execute"],
        risk_summary: { requires_approval: true },
      },
      messages: [],
      warnings: [],
      errors: [],
    });
    vi.mocked(saveReviewedPlan).mockResolvedValue({
      ok: true,
      reviewed_plan: {
        reviewed_plan_id: "plan-native-1",
        project_id: "project-1",
        project_config_path: "work/projects/demo/project_config.yaml",
        dataset_index_path: null,
        rawdata_dir: "work/projects/demo/rawdata",
        plan_hash: "hash",
        plan_path: null,
        status: "reviewed",
        created_at: "2026-06-25T00:00:00Z",
        updated_at: "2026-06-25T00:00:00Z",
        approval_status: "not_requested",
        execution_status: "not_started",
        last_audit_id: null,
        last_execution_id: null,
        warnings: [],
        payload: {},
      },
    });
    vi.mocked(checkApprovalGate).mockResolvedValue({
      ok: true,
      execution_allowed: true,
      approval_required: true,
      approved: true,
      missing_approval_nodes: [],
      rejected_nodes: [],
      errors: [],
      warnings: [],
    });

    renderConsole();

    await user.type(screen.getByRole("textbox"), "native full preprocessing");
    await user.click(screen.getByRole("button", { name: "Generate Plan" }));

    await screen.findByText("Native Preprocessing Safety Acknowledgement");
    await user.click(screen.getByRole("button", { name: "Approve all required nodes" }));
    await user.click(screen.getByLabelText(/I acknowledge native full preprocessing will run/i));
    await user.click(screen.getByLabelText(/external tools will not be executed/i));
    await user.click(screen.getByLabelText(/rawdata must remain read-only/i));
    await user.click(screen.getByLabelText(/native preprocessing risks/i));
    await user.click(screen.getByLabelText(/subject\/session scope has been reviewed/i));
    await user.click(screen.getByRole("button", { name: "Check Approval Gate" }));

    await waitFor(() => expect(checkApprovalGate).toHaveBeenCalledTimes(1));
    expect(checkApprovalGate).toHaveBeenCalledWith(
      "http://localhost",
      expect.objectContaining({
        approval: expect.objectContaining({
          approved: true,
          approved_nodes: ["native_preproc_full_execute"],
          native_preprocessing_acknowledgement: true,
          no_external_tools_confirmed: true,
          rawdata_read_only_confirmed: true,
          risk_acknowledgement: true,
          subject_scope_confirmed: true,
        }),
      }),
    );
  });
});
