from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def _read_json(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _function_exists(capabilities: dict[str, Any], name: str) -> bool:
    for item in capabilities.get("functions", []):
        if item.get("name") == name:
            return bool(item.get("exists"))
    return False


def run_dpabi_preflight(
    work_dir: str,
    report_dir: str,
    capabilities_path: str = "./work/dpabi/dpabi_capabilities.json",
    manifest_path: str = "./work/dpabi/dpabi_input_manifest.json",
    wrapper_config_template_path: str = "./work/dpabi/dpabi_wrapper_config_template.yaml",
) -> dict[str, Any]:
    warnings: list[str] = []
    errors: list[str] = []
    checks: list[dict[str, Any]] = []

    dpabi_work = Path(work_dir) / "dpabi"
    report_out = Path(report_dir) / "dpabi"
    dpabi_work.mkdir(parents=True, exist_ok=True)
    report_out.mkdir(parents=True, exist_ok=True)

    cap_path = Path(capabilities_path)
    man_path = Path(manifest_path)
    wrapper_path = Path(wrapper_config_template_path)

    capabilities = _read_json(cap_path)
    manifest = _read_json(man_path)

    def add_check(name: str, ok: bool, message: str, blocking: bool = True):
        checks.append({
            "name": name,
            "ok": ok,
            "message": message,
            "blocking": blocking,
        })
        if not ok and blocking:
            errors.append(message)
        elif not ok:
            warnings.append(message)

    add_check(
        "capabilities_json_exists",
        capabilities is not None,
        f"Capabilities JSON missing or invalid: {cap_path}",
    )

    add_check(
        "input_manifest_exists",
        manifest is not None,
        f"Input manifest missing or invalid: {man_path}",
    )

    add_check(
        "wrapper_config_template_exists",
        wrapper_path.exists(),
        f"Wrapper config template missing: {wrapper_path}",
        blocking=False,
    )

    dpabi_entry_found = False
    candidate_wrapper_found = False

    if capabilities:
        dpabi_entry_found = bool(
            capabilities.get("summary", {}).get("dpabi_entrypoint_found")
        ) or _function_exists(capabilities, "DPABI")

        candidate_wrapper_found = (
            _function_exists(capabilities, "DPARSF_run")
            or _function_exists(capabilities, "DPARSFA_run")
        )

    add_check(
        "dpabi_entrypoint_found",
        dpabi_entry_found,
        "DPABI entrypoint was not found.",
        blocking=False,
    )

    add_check(
        "candidate_wrapper_found",
        candidate_wrapper_found,
        "No candidate DPARSF_run or DPARSFA_run wrapper found. Full execution should not proceed without manual mapping.",
        blocking=False,
    )

    subjects_ready = 0
    ready_subjects: list[dict[str, Any]] = []

    if manifest:
        ready_subjects = [
            item for item in manifest.get("subjects", [])
            if item.get("status") == "READY_FOR_DPABI_DRY_RUN"
        ]
        subjects_ready = len(ready_subjects)

    add_check(
        "subjects_ready",
        subjects_ready > 0,
        "No subjects are ready for DPABI dry-run mapping.",
    )

    subject_checks: list[dict[str, Any]] = []

    for subject in ready_subjects:
        subject_id = subject.get("subject_id")
        t1w = subject.get("t1w")
        bold = subject.get("bold")
        tr = subject.get("tr")

        t1w_exists = bool(t1w and Path(t1w).exists())
        bold_exists = bool(bold and Path(bold).exists())
        has_tr = tr is not None

        item = {
            "subject_id": subject_id,
            "t1w_exists": t1w_exists,
            "bold_exists": bold_exists,
            "has_tr": has_tr,
            "tr": tr,
        }
        subject_checks.append(item)

        if not t1w_exists:
            errors.append(f"{subject_id}: T1w path missing: {t1w}")
        if not bold_exists:
            errors.append(f"{subject_id}: BOLD path missing: {bold}")
        if not has_tr:
            errors.append(f"{subject_id}: RepetitionTime missing.")

    workspace_dir = Path(work_dir) / "dpabi" / "dpabi_workspace"
    add_check(
        "workspace_exists",
        workspace_dir.exists(),
        f"DPABI workspace missing: {workspace_dir}",
    )

    batch_config_path = dpabi_work / "dpabi_batch_config_draft.yaml"

    batch_config = f"""# DPABI Batch Config Draft
# This file is generated by DPABI preflight.
# It is a draft only and must be reviewed before execution.

mode: "dry_run"
allow_full_preprocessing: false
require_manual_review: true

inputs:
  manifest: "{man_path}"
  subjects_ready: {subjects_ready}

dpabi:
  capabilities_json: "{cap_path}"
  dpabi_entrypoint_found: {str(dpabi_entry_found).lower()}
  candidate_wrapper_found: {str(candidate_wrapper_found).lower()}

workspace:
  root: "{workspace_dir}"
  outputs: "{workspace_dir / "outputs"}"
  logs: "{workspace_dir / "logs"}"

preprocessing:
  # Draft only. Do not execute without manual review.
  slice_timing: false
  realign: true
  normalize: true
  smooth: true
  nuisance_regression: false
  filter: false
  alff: false
  falff: false

safety:
  modify_rawdata: false
  delete_files: false
  modify_dpabi_source: false
"""
    batch_config_path.write_text(batch_config, encoding="utf-8")

    status = "PASS"
    if errors:
        status = "FAIL"
    elif warnings:
        status = "WARNING"

    report_json_path = dpabi_work / "dpabi_preflight_report.json"
    report_md_path = report_out / "dpabi_preflight_report.md"

    report = {
        "ok": status in {"PASS", "WARNING"},
        "node_id": "dpabi_preflight",
        "backend": "python",
        "status": status,
        "capabilities_path": str(cap_path),
        "manifest_path": str(man_path),
        "batch_config_draft": str(batch_config_path),
        "subjects_ready": subjects_ready,
        "checks": checks,
        "subject_checks": subject_checks,
        "warnings": warnings,
        "errors": errors,
    }

    report_json_path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    lines = []
    lines.append("# DPABI Preflight Report")
    lines.append("")
    lines.append(f"- Status: {status}")
    lines.append(f"- Subjects ready: {subjects_ready}")
    lines.append(f"- Capabilities: `{cap_path}`")
    lines.append(f"- Manifest: `{man_path}`")
    lines.append(f"- Batch config draft: `{batch_config_path}`")
    lines.append("")
    lines.append("## Checks")
    lines.append("")
    lines.append("| Check | OK | Blocking | Message |")
    lines.append("|---|---:|---:|---|")
    for check in checks:
        lines.append(
            f"| {check['name']} | {check['ok']} | {check['blocking']} | {check['message']} |"
        )
    lines.append("")
    lines.append("## Subject Checks")
    lines.append("")
    if subject_checks:
        lines.append("| Subject | T1w exists | BOLD exists | Has TR | TR |")
        lines.append("|---|---:|---:|---:|---:|")
        for item in subject_checks:
            lines.append(
                f"| {item['subject_id']} | {item['t1w_exists']} | {item['bold_exists']} | {item['has_tr']} | {item['tr']} |"
            )
    else:
        lines.append("No subjects ready for DPABI dry-run mapping.")
    lines.append("")
    lines.append("## Safety Note")
    lines.append("")
    lines.append("This preflight did not run DPABI preprocessing and did not modify rawdata or DPABI source code.")

    report_md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    return {
        "ok": report["ok"],
        "node_id": "dpabi_preflight",
        "backend": "python",
        "outputs": [
            str(batch_config_path),
            str(report_json_path),
            str(report_md_path),
        ],
        "metrics": {
            "status": status,
            "subjects_ready": subjects_ready,
            "checks_total": len(checks),
            "errors_count": len(errors),
            "warnings_count": len(warnings),
        },
        "warnings": warnings,
        "errors": errors,
    }
