from __future__ import annotations

import hashlib
import json
import os
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Protocol


GUI_ROOT = Path("outputs/work/gui_agent")
SUPPORTED_PROVIDERS = {"mock", "pywinauto"}


class GuiProvider(Protocol):
    provider_name: str

    def perform_step(self, session: dict[str, Any], action: str, parameters: dict[str, Any]) -> dict[str, Any]:
        ...

    def capture_screenshot(self, session: dict[str, Any], target_path: Path) -> dict[str, Any]:
        ...


@dataclass
class MockGuiProvider:
    provider_name: str = "mock"

    def perform_step(self, session: dict[str, Any], action: str, parameters: dict[str, Any]) -> dict[str, Any]:
        del session
        return {
            "executed": False,
            "provider_status": "MOCK_RECORDED",
            "notes": "Mock provider recorded the intended GUI action without controlling the desktop.",
            "action": action,
            "parameters": parameters,
        }

    def capture_screenshot(self, session: dict[str, Any], target_path: Path) -> dict[str, Any]:
        del session
        target_path.write_text(
            "Mock screenshot placeholder. Configure pywinauto provider to capture pixels.\n",
            encoding="utf-8",
        )
        return {"type": "screenshot_placeholder", "path": str(target_path)}


class PyWinAutoGuiProvider:
    provider_name = "pywinauto"

    def _desktop(self) -> Any:
        try:
            from pywinauto import Desktop
        except ImportError as exc:
            raise RuntimeError("Missing optional dependency: pywinauto. Install the gui extra.") from exc
        return Desktop(backend=os.environ.get("MEDIMAGE_GUI_AGENT_BACKEND", "uia"))

    def _window(self, session: dict[str, Any], parameters: dict[str, Any]) -> Any:
        title = parameters.get("window_title") or session.get("window_title") or session.get("target_app", ".*")
        return self._desktop().window(title_re=str(title))

    def perform_step(self, session: dict[str, Any], action: str, parameters: dict[str, Any]) -> dict[str, Any]:
        window = self._window(session, parameters)
        if action == "wait":
            time.sleep(float(parameters.get("seconds", 1.0)))
        elif action == "locate_window":
            window.wait("exists", timeout=float(parameters.get("timeout_seconds", 10)))
        elif action == "click":
            control = parameters.get("control")
            target = window[control] if control else window
            target.click_input()
        elif action == "type_text":
            text = str(parameters.get("text", ""))
            window.type_keys(text, with_spaces=True)
        elif action == "menu_select":
            menu_path = str(parameters.get("menu_path", ""))
            window.menu_select(menu_path)
        elif action == "record_observation":
            pass
        else:
            raise RuntimeError(f"Unsupported GUI action for pywinauto provider: {action}")

        return {
            "executed": action != "record_observation",
            "provider_status": "EXECUTED",
            "window_title": str(window.window_text()),
            "action": action,
            "parameters": parameters,
        }

    def capture_screenshot(self, session: dict[str, Any], target_path: Path) -> dict[str, Any]:
        window = self._window(session, {})
        image = window.capture_as_image()
        image.save(str(target_path))
        return {"type": "screenshot", "path": str(target_path), "window_title": str(window.window_text())}


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _session_dir(session_id: str) -> Path:
    if "/" in session_id or "\\" in session_id or ".." in session_id:
        raise ValueError("Invalid GUI Agent session_id.")
    return GUI_ROOT / "sessions" / session_id


def _stable_session_id(payload: dict[str, Any]) -> str:
    seed = json.dumps(payload | {"created_at": _now_iso()}, ensure_ascii=False, sort_keys=True).encode("utf-8")
    return "gui_" + hashlib.sha256(seed).hexdigest()[:12]


def _provider(name: str) -> GuiProvider:
    if name == "mock":
        return MockGuiProvider()
    if name == "pywinauto":
        return PyWinAutoGuiProvider()
    raise ValueError(f"Unsupported GUI provider: {name}")


def _write_replay_script(session: dict[str, Any]) -> str:
    base = _session_dir(session["session_id"])
    lines = [
        "# Reproducible GUI action log generated by MedImage Agent.",
        "# This script is an audit artifact; review before manual replay.",
        f"TARGET_APP = {session.get('target_app')!r}",
        f"OBJECTIVE = {session.get('objective')!r}",
        "STEPS = [",
    ]
    for step in session.get("steps", []):
        lines.append(
            "    "
            + repr(
                {
                    "index": step.get("index"),
                    "action": step.get("action"),
                    "parameters": step.get("parameters", {}),
                    "executed": step.get("executed", False),
                    "provider": step.get("provider"),
                }
            )
            + ","
        )
    lines += ["]", ""]
    path = base / "replay_steps.py"
    path.write_text("\n".join(lines), encoding="utf-8")
    return str(path)


def _write_session(session: dict[str, Any]) -> Path:
    base = _session_dir(session["session_id"])
    base.mkdir(parents=True, exist_ok=True)
    session["replay_script"] = _write_replay_script(session)
    path = base / "session.json"
    path.write_text(json.dumps(session, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def _read_session(session_id: str) -> dict[str, Any]:
    path = _session_dir(session_id) / "session.json"
    if not path.exists():
        raise FileNotFoundError(f"GUI Agent session not found: {session_id}")
    return json.loads(path.read_text(encoding="utf-8"))


def create_gui_agent_session(payload: dict[str, Any]) -> dict[str, Any]:
    session_id = payload.get("session_id") or _stable_session_id(payload)
    provider = payload.get("provider", os.environ.get("MEDIMAGE_GUI_AGENT_PROVIDER", "mock"))
    if provider not in SUPPORTED_PROVIDERS:
        raise ValueError(f"Unsupported GUI Agent provider: {provider}")

    target_app = payload.get("target_app", "spm")
    objective = payload.get("objective", "assist SPM/DPABI GUI operation")
    approved = bool(payload.get("approved", False))
    real_provider = provider != "mock"

    session = {
        "ok": True,
        "session_id": session_id,
        "status": "READY" if approved or not real_provider else "APPROVAL_REQUIRED",
        "provider": provider,
        "target_app": target_app,
        "objective": objective,
        "approved": approved,
        "created_at": _now_iso(),
        "updated_at": _now_iso(),
        "safety": {
            "scope": "SPM/DPABI GUI assistance only",
            "system_wide_automation": False,
            "rawdata_readonly": True,
            "requires_human_confirmation": real_provider,
            "mock_provider_default": provider == "mock",
        },
        "steps": [],
        "artifacts": [],
        "warnings": [] if approved or not real_provider else ["approved=true required before real GUI actions."],
        "errors": [],
    }
    session["session_path"] = str(_write_session(session))
    return session


def list_gui_agent_sessions() -> dict[str, Any]:
    sessions = []
    for path in sorted((GUI_ROOT / "sessions").glob("*/session.json"), reverse=True):
        try:
            item = json.loads(path.read_text(encoding="utf-8"))
            sessions.append({
                "session_id": item.get("session_id"),
                "status": item.get("status"),
                "provider": item.get("provider"),
                "target_app": item.get("target_app"),
                "objective": item.get("objective"),
                "updated_at": item.get("updated_at"),
            })
        except Exception:
            continue
    return {"ok": True, "sessions": sessions}


def step_gui_agent_session(session_id: str, payload: dict[str, Any]) -> dict[str, Any]:
    session = _read_session(session_id)
    action = payload.get("action", "record_observation")
    parameters = payload.get("parameters", {})

    if session.get("status") == "ABORTED":
        return {"ok": False, "session_id": session_id, "errors": ["Session is aborted."]}

    provider_name = session.get("provider", "mock")
    if provider_name != "mock" and not session.get("approved"):
        return {
            "ok": False,
            "session_id": session_id,
            "status": "APPROVAL_REQUIRED",
            "errors": ["approved=true is required before real GUI actions."],
        }

    step = {
        "index": len(session.get("steps", [])) + 1,
        "action": action,
        "parameters": parameters,
        "provider": provider_name,
        "executed": False,
        "created_at": _now_iso(),
    }

    try:
        provider_result = _provider(provider_name).perform_step(session, action, parameters)
        step.update(provider_result)
    except Exception as exc:
        step["provider_status"] = "FAILED"
        step["notes"] = str(exc)
        session.setdefault("errors", []).append(str(exc))
        session["status"] = "PAUSED_FOR_HANDOFF"
    else:
        session["status"] = "RUNNING"

    session.setdefault("steps", []).append(step)
    session["updated_at"] = _now_iso()
    session["session_path"] = str(_write_session(session))
    return {"ok": step.get("provider_status") != "FAILED", "session_id": session_id, "step": step, "session_path": session["session_path"], "replay_script": session["replay_script"]}


def capture_gui_agent_screenshot(session_id: str) -> dict[str, Any]:
    session = _read_session(session_id)
    provider_name = session.get("provider", "mock")
    if provider_name != "mock" and not session.get("approved"):
        return {
            "ok": False,
            "session_id": session_id,
            "status": "APPROVAL_REQUIRED",
            "errors": ["approved=true is required before real GUI screenshots."],
        }

    screenshots_dir = _session_dir(session_id) / "screenshots"
    screenshots_dir.mkdir(parents=True, exist_ok=True)
    suffix = "txt" if provider_name == "mock" else "png"
    path = screenshots_dir / f"screenshot_{len(session.get('artifacts', [])) + 1:03d}.{suffix}"
    artifact = _provider(provider_name).capture_screenshot(session, path)
    artifact["created_at"] = _now_iso()

    session.setdefault("artifacts", []).append(artifact)
    session["updated_at"] = _now_iso()
    _write_session(session)
    return {"ok": True, "session_id": session_id, "artifact": artifact}


def abort_gui_agent_session(session_id: str) -> dict[str, Any]:
    session = _read_session(session_id)
    session["status"] = "ABORTED"
    session["updated_at"] = _now_iso()
    session.setdefault("warnings", []).append("Session aborted by user/API request.")
    session["session_path"] = str(_write_session(session))
    return {"ok": True, "session_id": session_id, "status": "ABORTED", "session_path": session["session_path"]}
